sudo: true
language: cpp
compiler: 
  - g++ 
  - clang
os:
  - linux
  - osx

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get update -qq; fi

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then  sudo apt-get install -qq cmake; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export CXX="g++-4.8"; fi

script:
  - cmake --version
  - cmake .
  - make
  - ls test/bin/*
  - cd test/bin
  - ./fast_test


