sudo: true
language: cpp
compiler: 
  - g++ 
  - clang
os:
  - linux
  - osx

before_install:
  - source ./test/travis/env.sh

install:
  - source ./test/travis/setup.sh

script:
  - cmake --version
  - cmake .
  - make
  - ls test/bin/*
  - cd test/bin
  - ./fast_test


